### ISSUE TITLE
Data gone - no stats, no labels

### ISSUE THREAD

**Issue by HolubZnosA** [sasa95/pomodor#50]
This week I started to have a problem with my data - stats and labels. They are missing. Even if I add a new label, after page reload it is gone again.

**Comment by sasa95** [comment]
I've just found out that the Cloud Firestore quota has been exceed and that the billing plan should be upgraded. I tried upgrading but my card is not accepted. I'll see what I can do.

**Comment by sasa95** [comment]
This is resolved. Thank you for reporting!
