### ISSUE TITLE
Link broken : pomodor.app (DNS issue?)

### ISSUE THREAD

**Issue by MehdiChelh** [sasa95/pomodor#63]
Hello,

My brother @OEchchelh recommended the app to me, and it looks really cool indeed!

However, the link https://pomodor.app/ seems to be broken.
Is it normal?

Thanks!

**Comment by sasa95** [comment]
Hey there!

I'm switching the hosting from Netlify fo Firebase. The app will be down for a few hours, unfortunately.
I'll let you know when it's back online by closing the issue. 😉

**Comment by MehdiChelh** [comment]
Okay no problem 😉 thank you very much for your quick reply !

**Comment by sasa95** [comment]
@MehdiChelh It's fixed now. :)
